### PR TITLE
correct tries for more than 10 tries for aurora boards

### PR DESCRIPTION
**Pull request by lekanteto**
https://github.com/lemeryfertitta/BoardLib/issues/22

fixed with a hardcoded table similar to grades

### CODE REVIEW

**Comment by lekanteto** [comment]
sorry, mixed up some things that should not be in here. :-(

**Comment by lemeryfertitta** [comment]
@lekanteto no worries! If you did want to fix the attempts, I'd prefer not to hardcode. It's really easy to get the data from the db by just passing the `attempts` table to a sync request.

**Comment by lekanteto** [comment]
> @lekanteto  I'd prefer not to hardcode. It's really easy to get the data from the db by just passing the `attempts` table to a sync request.

Understood. I wanted to do it similar to the grades lookup that is already hardcoded even so there is a table in the database. 😉

```python
GRADES = {
    10: "4A",
    11: "4B",
    12: "4C",
    13: "5A",
    14: "5B",
    15: "5C",
    16: "6A",
    17: "6A+",
...
```

My current challenge is that there are values in the db table that I cannot choose in the official Kilterboard app. In the app I can choose a value between 1 and 100 for tries but the db table has those extra meanings above 10.🤔

```
1	1	Flash
2	2	2 tries
...
9	9	9 tries
10	10	10 tries
11	100	1 day
...
18	800	8 days
19	900	9 days
20	1000	10 days
21	10000	1 month
22	20000	2 months
...
31	110000	11 months
32	120000	12 months
33	1000000	1 year
...
37	5000000	5 years
0	0	Unknown
```

**Comment by lemeryfertitta** [comment]
>  I wanted to do it similar to the grades lookup that is already hardcoded even so there is a table in the database.

Had to support Moonboard, which doesn't run on Aurora's software. But its true there might be a cleaner way for just Aurora using their db.

> My current challenge is that there are values in the db table that I cannot choose in the official Kilterboard app. In the app I can choose a value between 1 and 100 for tries but the db table has those extra meanings above 10.

Mentioned it on the other thread, but it seems like maybe the behavior changed at some point. Maybe the attempts table is now just there for legacy purposes, and they are only doing bids?

**Pull request closed without merging**
